name: todo-github-actions
run-name: ${{ github.actor}} is runing the workflow now
on: 
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [7.0]
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NETCore ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }} 
      - name: Install dependencies
        run: dotnet restore
      - name: Build with dotnet 
        run: dotnet build --no-restore --configuration Release
      - name: Test with dotnet
        run: dotnet test --no-restore --verbosity quiet
      
      - name: Set up Qemu
        uses: docker/setup-qemu-action@v2
      - name: setup buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/minimal-api:latest
